### ISSUE TITLE
Malware inside

### ISSUE THREAD

**Issue by anthaeus** [jaredhaight/PSAttackBuildTool#10]
Downloads

    17.5 KB
    PSAttackBuildTool.zip
    Source code (zip)
    Source code (tar.gz)

are you sure you have forgotten to put a malware inside?
like it is asking to install a "NET" from http://dotnetsocial.cloudapp.net - come on IS IT EVEN a Micro$oft?

"No match for "DOTNETSOCIAL.CLOUDAPP.NET".
>>> Last update of whois database	Wed, 14 Sep 2016 08:58:51 GMT <<<"

if so, why doesn't even look like one.

what are the methods to build a psattack on linux? I am trying to do so on mona, however failing atm.

nice try, but yeah.. nice try :-) :+1:

**Comment by jaredhaight** [comment]
The build tool doesn't direct you to http://dotnetsocial.cloudapp.net. You can search the source here on Github, there's no reference to that domain. 

Doing some googling, this does appear to be a legit site, just poorly thought out on Microsoft's part. The actual .NET installers are downloaded from microsoft.com. For future reference, whois only works on domains, not subdomains. cloudapp.net is part of Microsofts Azure platform, but anyone can have a subdomain there so that doesn't legitimize the dotnetsocial website.

What operating system are on and what were you doing when you were directed to that domain? 

Building under Mona is not supported.

**Comment by jaredhaight** [comment]
Hey @anthaeus, I'm going to go ahead and close out this issue. Please re-open when you have more information.

Thanks!
